ALTER TABLE payments
ADD COLUMN status VARCHAR(10) NOT NULL DEFAULT 'PENDING';

ALTER TABLE payments
ADD CONSTRAINT status_check CHECK (status IN ('PENDING', 'PROCESSED', 'FAILED'));

ALTER TABLE payments
ALTER COLUMN processor DROP NOT NULL;
